Add videoUrl field
freeCodeCamp/curriculum pull request #298
Opened 2018-09-03 14:29 UTC by beaucarnes

Add vidoeUrl to responsive web design challenges.

2018-09-04 11:05 UTC, Bouncey commented on challenges/01-responsive-web-design/applied-visual-design.json
> +   c/Url": "",
Here is your linting error

2018-09-04 11:06 UTC, Bouncey requested changes

2018-09-04 11:06 UTC, Bouncey commented on challenges/01-responsive-web-design/applied-visual-design.json
> +   c/Url": "",
Here is your linting error

2018-09-04 11:08 UTC, Bouncey commented
@beaucarnes You have some linting errors, also you will need to update the challengeSchema to allow the videoUrl property to be a string, Joi may allow you to check a vaild url also? If it takes more than a minute of looking up I wouldn't worry about it too much.

2018-09-20 15:01 UTC, Bouncey requested changes
There have been some changes to the schema merged recently, you will need to rebase for those changes.

2018-09-20 15:01 UTC, Bouncey commented on schema/challengeSchema.js
> +  videoUrl: Joi.string(),
To allow for empty strings, this will need to be 
```js
Joi.string().allow('')
```

2018-09-20 15:02 UTC, Bouncey commented on schema/challengeSchema.js
> +  videoUrl: Joi.string(),
CI failed on `videoUrl: ''`

2018-09-25 15:11 UTC, raisedadead approved these changes

2018-09-25 15:12 UTC, merged

2018-09-25 15:12 UTC, raisedadead commented
Nice work. Thanks @beaucarnes

2018-09-25 15:19 UTC, raisedadead commented
:tada: This PR is included in version 3.2.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@freecodecamp/curriculum)
- [GitHub release](https://github.com/freeCodeCamp/curriculum/releases/tag/v3.2.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: